# Generated by Django 3.1.7 on 2021-03-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
